'use client'

import AnimatedContainer from '@/components/shared/AnimatedContainer'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import {
  faLeaf,
  faExclamationTriangle,
  faTint,
  faChartLine,
} from '@fortawesome/free-solid-svg-icons'

export default function DashboardPage() {
  return (
    <div className="space-y-6">
      {/* 🌿 Greeting */}
      <AnimatedContainer>
        <div>
          <h2 className="text-2xl font-semibold tracking-tight">
            Welcome back 👋
          </h2>
          <p className="text-sm text-foreground/70 mt-1">
            Here’s what’s happening with your plants today.
          </p>
        </div>
      </AnimatedContainer>

      {/* 🌱 Stats Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        {stats.map((stat, index) => (
          <AnimatedContainer key={stat.label} delay={index * 0.1}>
            <div className="glass rounded-2xl p-5 border border-white/10 hover:shadow-glow transition">
              <div className="flex items-center justify-between">
                <span className="text-sm text-foreground/60">{stat.label}</span>
                <span className="text-verdant-400 text-lg">{stat.icon}</span>
              </div>

              <p className="text-2xl font-semibold mt-3">{stat.value}</p>

              <p className="text-xs text-foreground/60 mt-1">{stat.sub}</p>
            </div>
          </AnimatedContainer>
        ))}
      </div>

      {/* 🌿 Main Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* 🌱 Recent Activity */}
        <AnimatedContainer className="lg:col-span-2">
          <div className="glass rounded-2xl p-6 border border-white/10 h-full">
            <h3 className="text-lg font-semibold mb-4">Recent Activity</h3>

            <div className="space-y-4">
              {activities.map((activity) => (
                <div
                  key={activity.id}
                  className="flex items-start gap-3 p-3 rounded-xl hover:bg-white/5 transition"
                >
                  <div className="text-verdant-400 mt-1">{activity.icon}</div>

                  <div>
                    <p className="text-sm font-medium">{activity.title}</p>
                    <p className="text-xs text-foreground/60">
                      {activity.time}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </AnimatedContainer>

        {/* 🌿 Quick Insights */}
        <AnimatedContainer delay={0.2}>
          <div className="glass rounded-2xl p-6 border border-white/10 h-full flex flex-col justify-between">
            <div>
              <h3 className="text-lg font-semibold mb-4">AI Insight</h3>

              <p className="text-sm text-foreground/70 leading-relaxed">
                Your Monstera may need watering tomorrow. Humidity levels are
                slightly low—consider misting.
              </p>
            </div>

            <div className="mt-6 text-xs text-foreground/50">
              Generated by AI • Updated just now
            </div>
          </div>
        </AnimatedContainer>
      </div>
    </div>
  )
}

/* 🌿 MOCK STATS */
const stats = [
  {
    label: 'Total Plants',
    value: '12',
    sub: '+2 this week',
    icon: <FontAwesomeIcon icon={faLeaf} />,
  },
  {
    label: 'Needs Attention',
    value: '3',
    sub: 'Watering overdue',
    icon: <FontAwesomeIcon icon={faExclamationTriangle} />,
  },
  {
    label: 'Watered Today',
    value: '5',
    sub: 'Good consistency',
    icon: <FontAwesomeIcon icon={faTint} />,
  },
  {
    label: 'Health Score',
    value: '87%',
    sub: 'Overall condition',
    icon: <FontAwesomeIcon icon={faChartLine} />,
  },
]

/* 🌱 MOCK ACTIVITY */
const activities = [
  {
    id: 1,
    title: 'Scanned Monstera — No disease detected',
    time: '2 hours ago',
    icon: <FontAwesomeIcon icon={faLeaf} />,
  },
  {
    id: 2,
    title: 'Watered Snake Plant',
    time: '5 hours ago',
    icon: <FontAwesomeIcon icon={faTint} />,
  },
  {
    id: 3,
    title: 'AI suggested fertilizer update',
    time: 'Yesterday',
    icon: <FontAwesomeIcon icon={faChartLine} />,
  },
]
